# Generated by Django 5.0.6 on 2024-06-22 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_student_user_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('bio', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=250)),
                ('phonenumber', models.CharField(max_length=250)),
                ('profileimage', models.ImageField(upload_to='student_profile/')),
                ('student', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Student_Profile',
        ),
    ]
