# Generated by Django 5.0.6 on 2024-06-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_teacher_delete_student_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_description', models.CharField(max_length=255)),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('students', models.ManyToManyField(related_name='students', to='api.student_teacher')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='api.student_teacher')),
            ],
        ),
    ]
