# Generated by Django 5.0.6 on 2024-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_skills_course_delete_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='skill',
            field=models.ManyToManyField(related_name='skills', to='api.skills'),
        ),
    ]
