# Generated by Django 5.0.7 on 2024-08-25 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_course_overview_course_course_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='api.skill'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrolled_courses', to='api.studentteacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to='api.studentteacher'),
        ),
    ]
